/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import DataBaseCon.DataBaseOperations;
import RegValidations.RegisterValidations;
import gettersetter.RegisterModelEncapsulation;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RegisterEmployee extends javax.swing.JFrame {
    private Object jbutton1;

    /**
     * Creates new form RegisterEmployee
     */
    public RegisterEmployee() {
        initComponents();
     //   setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        EmailId = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        PhoneNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Employee");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ER.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 430, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 46, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackButtionIcon.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 80, 57));

        Name.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 76, 368, 47));

        EmailId.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(EmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 202, 368, 47));

        Password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 350, 368, 47));

        buttonGroup3.add(Female);
        Female.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Female.setForeground(new java.awt.Color(0, 255, 0));
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        buttonGroup3.add(Male);
        Male.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Male.setForeground(new java.awt.Color(102, 255, 0));
        Male.setText("Male");
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        PhoneNo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(PhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 368, 47));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("Email Id :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 172, 114, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Password :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 320, 114, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 0));
        jLabel10.setText("Phone No. :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 114, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 0));
        jLabel11.setText("Enter Name :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 46, 114, -1));

        RegisterButton.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(0, 0, 153));
        RegisterButton.setText("Register");
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseEntered(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusIcon.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, 61));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newBg01 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new AdminPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // ---------------------------First we have to get the value from the respected textfield.----------------------------------
        String name1=Name.getText();
        String email1=EmailId.getText();
        char[] pass1=Password.getPassword();
        String pass2=String.valueOf(pass1);
        
        String gender1="";
        
        if(Male.isSelected())
        {
            gender1 = "M";
        }
         if(Female.isSelected())
        {
            gender1 = "F";
        }
       
         String phone_no = PhoneNo.getText();
         String module1 = "Employee";
         
       /*  if(EnterName.equals(" "))
         {
             JOptionPane.showMessageDialog(rootPane,"Please Enter Name","Name Error",JOptionPane.ERROR_MESSAGE);
         }*/
         //------------------------------Database Connection----------------------------
            // ---------first way to optimize the RegisterEmployee code---------------
          
            RegisterValidations rv = new RegisterValidations();
            
            if(! rv.nameValidation(name1))          // as we provided ! mark means not i.e false which shows the message which we set in th is block .
            {
                JOptionPane.showMessageDialog(rootPane,"Invalid Name");
            }
            else if( ! rv.emailValidation(email1))
            {
                JOptionPane.showMessageDialog(rootPane,"Invalid Email Id");
            }
            else if( ! rv.passwordValidation(pass2))
            {
                JOptionPane.showMessageDialog(rootPane,"Invalid Password");
            }
            else if( ! rv.phone_noValidation(phone_no))
            {
                JOptionPane.showMessageDialog(rootPane,"Invalid Phone Number");
            }
            
            else
            {
                 RegisterModelEncapsulation reg = new RegisterModelEncapsulation();               // user define class which include getter and setter method which provider the security.

                reg.setName(name1);
                reg.setEmail(email1);
                reg.setPassword(pass2);
                reg.setGender(gender1);
                reg.setPhoneNo(phone_no);
                reg.setModule(module1);
                 // pass reference variable reg which is a instance of class Register into the software method which we declared in DataBaseConnection.
                boolean reg_emp = DataBaseOperations.software(reg);

                if(reg_emp == true)
                {
                    JOptionPane.showMessageDialog(rootPane,"Employee Register Successfully...!!!");

                    Name.setText("");
                    EmailId.setText("");
                    Password.setText("");
                    buttonGroup3.clearSelection();
                    PhoneNo.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Employee Unable to Register Due to Some Errors","Register Error",JOptionPane.ERROR_MESSAGE);
                }
            
            }
           
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
      if(Name.getText()==null && EmailId.getText()==null )
       {
           JOptionPane.showMessageDialog(rootPane, "Employee unable to register..! Please Enter the information.");
       }
   
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void RegisterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseEntered
        /* TODO add your handling code here:
            if(EnterName.getText()==null && EmailId.getText()==null )
       {
           JOptionPane.showMessageDialog(rootPane, "Employee unable to register..! Please Enter the information.");
       } */
    }//GEN-LAST:event_RegisterButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailId;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JButton RegisterButton;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
